name: "GTFS Release"

# 手動で実行
on: workflow_dispatch

# Releaseの書き込み権限付与
permissions:
    contents: write

jobs:
    gtfs-release:
        
        runs-on: ubuntu-latest

        steps:
        
        # リポジトリをクローン 
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            fetch-depth: 1

        # PythonのSetup
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
            architecture: 'x64'

        # 依存パッケージのインストール
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
        
        # スクリプトの実行
        - name: Run script
          run: |
            poetry run python src/main.py
        
        # 日付の取得
        - name: Set current date as env
          env:
            TZ: 'Asia/Tokyo' # タイムゾーンの指定
          run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
        # Releaseの作成
        - name: Create Release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ env.CURRENT_DATE }}
            artifacts: "dist/*.gtfs.zip"